sudo: required
language: generic

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=24
    - OS_TYPE=centos OS_DIST=el OS_VERSION=7

services:
  - docker

install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

deploy:
  provider: packagecloud
  repository: repository
  username: abn
  dist: ${OS_DIST}/${OS_VERSION}
  skip_cleanup: true
  token:
    secure: LZkyz54fpAzyriAIVtpx9rWA79iUVEqzdm+Q/w8X7v4H/a3lCy5jhbURgkr78nORPYaH02/xAkBDAA/4BvH+Trc1EoF3VC6q3uup9Rjp0U2+42ZHYM/Bf3a2ccy6d4ytVG50fjiL4KLkXKbBl3iFaWHj5YN8HsYB8z8kJ1KGERbCfCU2DJTdS8db9eeysfySy+ZCNwbQh5QrXjyz/TSVg+5bAt/S17UMvtpTlLT53So49xS5HipmOFg7vqDRCDYIemKQkq+ou/cAX0UtJqYqJKL6xCEhxBNNkA+/GEX1inJddaIaVHDzDsfWk7W4Hx03qQwaxcUi5E2EA4qZQuKNZErT8ihxYoMWXGpLsgxgrDs4IyytSJvolz58LRKseRlutNvBWKh4UfCDolRAXO7KWqJxvkXpdPsnjKbBONpPeeVSvZslV35EH2SstFb68gKdjTfQAxt/TEjpJwk4qGhazX9R1tpGm+t2X2Qi8+ujInNWyGfaBJR8J+lxeC8wjwpozuES1iebOZDET2n0tAVjJ4q0UTJ4OefYMzMSlzb3y1pOd0DI8soqx9TyBZ7z+C5XLj2FLjZMKaRWwN5iGWqexALNxhfHsElm7yHw2FhSi4vEKBLdJwbzvTibkzeDsgavOzD13E3eJO1wibhC3InnolPH0zRA0zcc7Ch5v+R8CPk=
  on:
    tags: true
